### ISSUE TITLE
failed to compile br-index

### ISSUE THREAD

**Issue by shenwei356** [algbio/efg-mems#1]
Hi,  the commands in the [installation](https://github.com/algbio/efg-mems#installation) section did not work. It should be due to br-index. However, it was hard to install br-index.

**Comment by shenwei356** [comment]
`br-index` can be compiled now: https://github.com/U-Ar/br-index/issues/4 .

The [installation](https://github.com/algbio/efg-mems#installation) might needs a small change:

    ./install.sh   ->   ./install.sh .

Also, `CMakeLists.txt` in br-index/ needs to be edited.

There's another small typo stopping to compile efg-mems:

The path https://github.com/algbio/efg-mems/blob/c0dd6905a6dd1a1990e46bdbd55e4429bdde9674/bdbwt2brindex.hpp#L6

should be 

    #include "../bdbwt/include/BD_BWT_index.hh"

**Comment by velimakinen** [comment]
Fixed the efg-mems related parts, but left the installation of br-index to the user.

**Comment by velimakinen** [comment]
Modified README to instruct installing br-index before running the scripts.
